### ISSUE TITLE
Kargo Barkodu

### ISSUE THREAD

**Issue by ismailua** [beratkrdr/yurtici-kargo-entegrasyon-php#2]
Merhaba,
Güzel paylaşım olmuş teşekkürler. Kargonun ShippingOrderDispatcherServices?wsdl linki üzerinde XEDocCargo, XEDocCargoZplFormatData şeklinde parametreler gördüm. Gönderiler için otomatik barkod oluşturuluyor mu? bu parametlerden acaba barkod dönüşleri mi oluyor? sizce barkodları nasıl alabiliriz?

**Comment by beratkrdr** [comment]
Merhabalar, dediğiniz parametreleri ben göremedim acaba bir link veya görsel iletme şansınız var mı?

**Comment by ismailua** [comment]
http://testwebservices.yurticikargo.com:9090/KOPSWebServices/ShippingOrderDispatcherServices?wsdl
linki üzerinde XEDocCargoZplFormatData ve XEDocCargo olarak yer almakta. Kargo barkodlarını alabileceğimizi düşündüm.
Bu alanları nasıl kullanabiliriz acaba?

**Comment by beratkrdr** [comment]
Ufak bir araştırma yaptım fakat buna dair bir şey bulamadım. Daha sonra tekrar araştırıcam eğer bulabilirsem size dönüş yaparım.

**Comment by ismailua** [comment]
Teşekkürler.
